services:
  - type: web
    name: postproject-backend
    env: node
    plan: free
    rootDir: market-backend
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
