services:
  - type: web
    name: postproject-backend
    env: node
    plan: starter  # Free plan may be too small for NestJS
    rootDir: market-backend
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node --max-old-space-size=1024 ./dist/main.js
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: ${PORT}  # Let Render assign the port
